CALM_TRIGGERS = {
    "breath",
    "breathe",
    "relax",
    "pause",
    "stillness",
    "calm",
    "settle",
    "release",
    "soften",
    "acknowledge",
    "accept",
    "reflect",
    "present",
    "let go",
    "feel",
    "see",
    "ground",
    "hear",
    "sense",
    "imagine",
    "allow",
    "embrace",
    "welcome",
    "trust",
    "surrender",
    "open",
    "expand",
}

# Used to identify where to add pauses in the TTS.
