services:
  minday-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: minday-backend:dev
    container_name: minday-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./api:/app/api
      - ./config:/app/config
      - ./assets:/app/assets
    secrets:
      - GEMINI_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    environment:
      - GEMINI_API_KEY_FILE=/run/secrets/GEMINI_API_KEY
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/AWS_SECRET_ACCESS_KEY
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

secrets:
  GEMINI_API_KEY:
    file: ./secrets/GEMINI_API_KEY
  AWS_ACCESS_KEY_ID:
    file: ./secrets/AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    file: ./secrets/AWS_SECRET_ACCESS_KEY
